version: "3"
networks:
    vlinux:

services:
    server:
        image: "fridavbg/bthloggen-server:1.0"
        volumes:
            - "./data:/data/"
        container_name: bthloggen-server
        ports:
            - "1337:1337"
        networks:
            vlinux:
        restart: "always"
    client:
        image: "fridavbg/bthloggen-client:1.0"
        container_name: bthloggen-client
        networks:
            vlinux:
        links: 
            - server:bthloggen-server
    webbclient:
        image: "fridavbg/bthloggen-webbclient:1.0"
        container_name: bthloggen-webbclient
        volumes:
            - "./webbclient/kmom10.vlinux.se"
        ports:
            - "127.0.0.1:1338:80"
        extra_hosts:
            - "kmom10.vlinux.se:127.0.0.1"
        networks:
            vlinux:
        links: 
            - server:bthloggen-server