version: "3"
networks:
    dbwebb:

services:
    server:
        image: "fridavbg/bthloggen-server:1.0"
        volumes:
            - "./data:/server/data/"
        container_name: Kmom10server
        ports:
            - "1337:1337"
        networks:
            dbwebb:
        restart: "always"
    client:
        image: "fridavbg/bthloggen-client:1.0"
        container_name: kmom10client
        networks:
            dbwebb:
        links: 
            - server:Kmom10server